name: verify
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test-linux-gpu:
    runs-on: "my-special-gpu-friend"
    steps:
      - name: can I run docker with gpus to an assigned GPU?
        run: docker run --rm -it --gpus="device=$(cat ~/.assigned_gpu)" pytorch/pytorch nvidia-smi
